add mysql

diff --git a/.github/workflows/dev-cicd-aws.yaml b/.github/workflows/dev-cicd-aws.yaml
--- a/.github/workflows/dev-cicd-aws.yaml
+++ b/.github/workflows/dev-cicd-aws.yaml
@@ -28,7 +28,7 @@ jobs:
           --health-timeout=5s
           --health-retries=3  
     steps:
-    - name: Source Code Checkout
+    - name: 소스코드 다운로드
       uses: actions/checkout@v4 
 
     - name: Set up JDK 17
@@ -36,5 +36,21 @@ jobs:
       with:
         java-version: '17'
         distribution: 'temurin'
-    - name: Run test java
+    - name: 테스트수행
       run: ./gradlew test
+
+    - name: 테스트 검사 후 실패시 파이프라인 중단
+      if: failure()
+      run: |
+        echo "Tests failed! Pipeline will be stopped."
+        exit 1
+
+    - name: 테스트 결과를 STEP Summary에 업로드
+      if: always()
+      uses: actions/upload-artifact@v4
+      with:
+        name: test-report
+        path: |                    # 여러 경로 지정
+          **/build/reports/tests/test/
+          **/build/test-results/test/
+        retention-days: 30 
